spring.application.name=apiGateway
server.port=${API_GATEWAY_PORT}
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.reactor.netty=INFO
logging.level.org.springframework.web=DEBUG
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.enabled=true
management.info.env.enabled=true
internal.api-key=${INTERNAL_API_KEY}

