spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:${AUTH_APP_PORT}/api/auth/.well-known/jwks.json

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:${AUTH_APP_PORT}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:${USER_APP_PORT}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**, /api/cards/**

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=http://localhost:${ORDER_APP_PORT}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**, /api/items/**

# URL ??? WebClient (SAGA)
microservices.auth-url=http://localhost:${AUTH_APP_PORT}
microservices.user-url=http://localhost:${USER_APP_PORT}