spring.application.name=apiGateway
server.port=8084
logging.level.org.springframework.web=DEBUG

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8080}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=${USER_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**, /api/cards/**

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=${ORDER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**, /api/items/**

microservices.auth-url=${AUTH_SERVICE_URL:http://localhost:8080}
microservices.user-url=${USER_SERVICE_URL:http://localhost:8081}

internal.api-key=${INTERNAL_API_KEY}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVICE_URL:http://localhost:8080}/api/auth/.well-known/jwks.json
